services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-main
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - shared-infra-net

  minio:
    image: minio/minio:latest
    container_name: minio-main
    restart: unless-stopped
    env_file: .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - shared-infra-net

  minio-create-bucket:
    image: minio/mc
    container_name: minio-create-bucket-main
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      mc ls minio/mlflow || mc mb minio/mlflow
      "
    env_file: .env
    restart: "no"
    networks:
      - shared-infra-net
      

  litellm:
    image: ghcr.io/berriai/litellm-database:main-stable
    container_name: litellm-main
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${LITELLM_POSTGRES_USER}:${LITELLM_POSTGRES_PASSWORD}@postgres:5432/${LITELLM_POSTGRES_DB}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}


    # # ----  LangSmith Integration ----
    # - LANGSMITH_API_KEY=${LANGSMITH_API_KEY} # Standard key name
    # - LANGSMITH_PROJECT=${LANGSMITH_PROJECT} # Standard project name
    # - LANGSMITH_TRACING=true                  # Required for tracing
    # - LANGSMITH_BATCH_SIZE=1                 # Set to 1 to see traces instantly in dev
    volumes:
      - ./configs/litellm-config.yaml:/app/litellm-config.yaml
    ports:
      - "4000:4000" # Proxy accessible at http://localhost:4000
    command: ["--config", "/app/litellm-config.yaml"]
    depends_on:
      - postgres
      - ollama
    networks:
      - shared-infra-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-main
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # or 1, if you have multiple GPUs
              capabilities: [gpu]
    networks:
      - shared-infra-net

#################
# Volumes
#################
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: F:\docker-images\volumes\pg_data

  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: F:\docker-images\volumes\minio_data

  ollama_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: F:/docker-images/volumes/ollama_data




#################
# Networking
#################
networks:
  shared-infra-net:
    name: shared-infra-net  # Forces the exact network name
    driver: bridge