litellm_settings:
  success_callback: ["langsmith"]
  failure_callback: ["langsmith"]


model_list:
  - model_name: gemma2b
    litellm_params:
      model: ollama/gemma2:2b
      api_base: "http://ollama:11434"
    tpm: 100000  # Local models don't really have limits, but helpful for routing

  - model_name: gemma4e4b
    litellm_params:
      model: ollama/gemma4:e4b
      api_base: "http://ollama:11434"
    tpm: 100000  # Local models don't really have limits, but helpful for routing
